# let's see if we can get travis to work using containers
language: c

# only run for pushes to the master branch
branches: 
  only: 
   - master

# install add-ons
addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base-dev

# cache where R stores its libraries
cache:
  directories: 
    - ~/Rlib

# - create .Renviron with location of R libraries
# - install devtools if not already installed
# - install matchingR with dependencies
install:
  - mkdir -p ~/Rlib 
  - echo 'R_LIBS=~/Rlib' > .Renviron
  - Rscript -e 'if(!"devtools" %in% rownames(installed.packages())) { install.packages("devtools", repos="http://cran.rstudio.com/") }'
  - Rscript -e 'devtools::install(pkg = ".", dependencies = TRUE)'

# run devtools::test() and see if the package passes all the tests
script: 
  - Rscript -e 'devtools::test()'
  - rm -f -r ~/Rlib/matchingR

# if everything worked out, then report coverage rate to coveralls
after_success:
  - Rscript -e 'if(!"covr" %in% rownames(installed.packages())) { devtools::install("covr", dependencies=TRUE) }'
  - Rscript -e 'covr::coveralls(exclusions = "src/RcppExports.cpp")'

# send e-mails if stuff changes
notifications:
  email:
    on_success: change
    on_failure: change
