language: c
branches:
  only:
  - master
env:
  global:
  - secure: SVR0tIJ5VSGSdoz7/+Ur+AmUg2dJHaqHd00MhIazsmh9V6QD/D6tdw1SRxetYLgIZD0/0XJuz5O4g5n8vCDwJKxPds2QY7m+iykmYyjgOWOXqQQoIvecwI0mKVPAzJf3iEnRsJ6xg+46gcqYONGIQeiV5Yr4CAXYQGqvhWt7NgceXglHjX/qFREH4RSHd4nMVsH2OkDfRsXdLCyLPX44uIjjwtgfBs7X4bjDy5PlyzyYEAVAJWeO/Q6IelX7iaEoMr+TI+KZiw23yy3wU8B3/eAJzgJHQqny9XFkVC8P5AtBYQN2Ia1G0rxwD1ofoDEbonDuKGVdbJrV4eNpUlpfuiWQBSTURX8WuVisGMLhGogAb8WwnfZVg6yNlK8oJjyne5aNeSFzX81YIlw1tWzNvpd46RWCGbYOoXjZtK2E8+SPBWw0R/1ay6PLtZh8vwn6odyKJFE3BHI/zDfv9GarSeubjs2FPPSVSR8P0E8kl3BzXaGC1mDlFloLhDZ7XDTp48RpZHOlfVemZxwG2Kx7swe0l3Lk2QkeaJ8Vk33ZwA+pUPX+4uNUgcxX3xkbnJtmsSf1n0g9hn9/EpWYAlsPLU6Tnhac/wZJx9+JQYaVTkSDEeBe8REmnT8pk1QTspJcfPfgntWuaGrnU6F5g0oK0l0OCDn04BUrjZRTGbdV1uc=
  - BOOTSTRAP_LATEX=1 BOOTSTRAP_PANDOC=1  
sudo: required
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- "./travis-tool.sh bootstrap"
install:
- mkdir ~/.R
- "./travis-tool.sh RInstall crayon"
- "./travis-tool.sh install_github jimhester/covr"
- "./travis-tool.sh install_deps"
script: "./travis-tool.sh run_tests"
after_failure:
- "./travis-tool.sh dump_logs"
after_success:
- Rscript -e 'library(covr);coveralls()'
- export REPO_NAME=${TRAVIS_REPO_SLUG#*/}
- Rscript -e "install.packages('rmarkdown', repos='http://cran.rstudio.com')"
- R CMD Rd2pdf ${TRAVIS_BUILD_DIR} -o ${TRAVIS_BUILD_DIR}/${REPO_NAME}.pdf
- R CMD INSTALL ${TRAVIS_BUILD_DIR}
- cd ${TRAVIS_BUILD_DIR}
- Rscript -e "library('rmarkdown'); for(file.name in dir(path = 'vignettes/', pattern
  = '*.Rmd')) { render(paste('vignettes', file.name, sep='/'), output_file = gsub('Rmd',
  'html', file.name), output_format = 'html_document') }"
- cd ..
- git clone https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
- cd gh-pages
- git config user.name "Jan Tilly"
- git config user.email "jantilly@gmail.com"
- git checkout gh-pages
- git pull origin gh-pages
- mv ${TRAVIS_BUILD_DIR}/${REPO_NAME}.pdf .
- mv ${TRAVIS_BUILD_DIR}/vignettes/*.html .
- git add ${REPO_NAME}.pdf
- git add *.html
- git commit -m "Automatic Travis update of PDF documentation and vignettes"
- git push origin gh-pages
notifications:
  email:
    on_success: change
    on_failure: change
