# let's see if we can get travis to work with native r support
language: c

# only run for pushes to the master branch
branches: 
  only: 
   - master

# set a secure key to push documentation to gh-pages branch
env: 
  global: 
   - secure: me7OtR6CI2HsNhk+V0H9QJbIFlbKmhc9iyYHak7Bc7jQOKYfZAEFB5YkqWe4/KLiNCKBKtKhpGI3ZHXj0Df9JlxOuCs9zlFY4365hDV9iYiNBM20eYXqPAJ9xvZ1ADLhHB4VVmeSDII63EJBgesGIHSSAFZ84SKhMWT4jYbeb35MN6VA29T0fP1tab903jhYIhp33Ibjdgbu7kh4Fx5j1PE0/G8uqHpJ2DU0l26nBoSzMmFrQUv9gUPAPcZnxuAHIxqxHWYfbO3k4aI39qy8BrVbyNt5JUYpcRTAmySg0Q/68SL86cW582dXzaG+TZjR/R7e+6/pOqcskdQe7wTxgew5EbwciSnonnapNhHvmoWMoZCR1aFDrNfIucmUhiKbeMQjO+T6sEoLlRnWUEKXk+hv0RQIQbxa5iiVqGdCikw9G0RyV4o7yAapkycWdBxxqQeOcC8kmtRtHJJrNGgXKfu8m4KirCS/X4s6SiFR8rCWvYMnMtNGjRxIoVdVkscWk76SvWyAxDadOQcR7waJ+WTsiKXfek3niuebwObEh/q14bxHGBK6+k33Z4AT108jVnpcmKRkeAqgDQSqo3Bny1nKHbI1G3twl2+W68L2v54rEdtl4LZTrWbXby0/C975nAvrGK1KJh4sLvJUL7snj9frxMyB20PknpvoxJIW4gA=

addons:
  apt:
    packages:
    - r-base
    - r-recommended

install:
  - Rscript -e 'install.packages("~/matchingR")'
  
script: 
  - Rscript -e 'install.packages("devtools"); devtools::test()'

# install covr package from CRAN
r_packages:
 - Rcpp
 - RcppArmadillo
 - devtools
 - testthat
 - knitr
 - microbenchmark
 - crayon
 - rmarkdown
 - covr
 
# if everything worked out, then report coverage to coveralls and then 
# push the documentation and vignettes to the gh-pages branch
after_success:
- Rscript -e 'covr::coveralls(exclusions = "src/RcppExports.cpp")'

# send e-mails if stuff changes
notifications:
  email:
    on_success: change
    on_failure: change
