# .travis.yml for matchingR using container-based infrastructure

# use c as catch-all language
language: c

# use containers
sudo: false

# define environmental variables for R CMD check
env:
  global:
    - _R_CHECK_CRAN_INCOMING_=FALSE
  matrix:
    - FLAGS = -O0 -g -Wall -Werror -pedantic -ftrapv
    - FLAGS = -O2

before_install:
  - export PATH=$HOME/bin:$HOME/texlive/bin/x86_64-linux:$PATH

# only run for pushes to master branch
branches:
  only:
   - master

# install r-base-dev:
# use r-packages-precise (https://cran.r-project.org/bin/linux/ubuntu/precise/) as source
# which is white listed (https://github.com/travis-ci/apt-source-whitelist/)
# also install latex, pandoc, qpdf and valgrind
addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base-dev
    - r-recommended
    - texinfo
    - lmodern
    - qpdf
    - valgrind

# cache local R libraries directory:
cache:
  directories:
    - ~/Rlib
    - $HOME/texlive
    - $HOME/bin

# install the package and dependencies:
# use Yihue's compiled texlive and pandoc versions (https://github.com/yihui/knitR/blob/master/.travis.yml)
install:
  - "[ ! -d ~/bin ] && mkdir ~/bin || true"
  - "wget -q -O - https://github.com/yihui/crandalf/raw/master/inst/scripts/install-texlive | bash"
  - "wget -q -O - https://github.com/yihui/crandalf/raw/master/inst/scripts/install-pandoc | bash"
  - mkdir -p ~/Rlib
  - echo 'R_LIBS=~/Rlib' > .Renviron
  - echo 'options(repos = "http://cran.rstudio.com")' > .Rprofile
  - echo '.travis.yml' > .Rbuildignore
  - Rscript -e 'if(!"devtools" %in% rownames(installed.packages())) { install.packages("devtools", dependencies=TRUE, repos="http://cran.rstudio.com/", lib="~/Rlib") }'
  - Rscript -e 'if(!"covr" %in% rownames(installed.packages())) { install.packages("covr", dependencies=TRUE, repos="http://cran.rstudio.com/", lib="~/Rlib") }'
  - Rscript -e 'if(!"testthat" %in% rownames(installed.packages())) { install.packages("testthat", dependencies=TRUE, repos="http://cran.rstudio.com/", lib="~/Rlib") }'
  - Rscript -e 'update.packages(ask = FALSE, instlib = "~/Rlib")'
  - Rscript -e 'devtools::install_deps(pkg = ".", dependencies = TRUE)'
  - mkdir -p ~/.R
  - echo "CCFLAGS = ${FLAGS}" > ~/.R/Makevars
  - echo "CXXFLAGS = ${FLAGS}" >> ~/.R/Makevars

# build, check, and install package
# run all examples and the vignettes through valgrind
script:
  - R CMD build . 
  - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
  - R CMD check "${PKG_FILE_NAME}" --as-cran 
  - R CMD INSTALL "${PKG_FILE_NAME}"
  - R -d valgrind --no-save < matchingR.Rcheck/matchingR-Ex.R
  - R -d valgrind --no-save < matchingR.Rcheck/matchingR/doc/matchingR-intro.R

# report coverage rate to coveralls
after_success:
  - Rscript -e 'covr::coveralls(exclusions = list("src/RcppExports.cpp", "R/deprecated.R"))'

# send e-mails if stuff changes
notifications:
  email:
    on_success: change
    on_failure: change
